<p>
	<?php echo $this->tag->linkTo(["admin{$plural}/new", '<i class="fa fa-plus"></i> ADD NEW', "class" => "btn btn-primary"]); ?>  
</p>

<?php if(count($page->items) > 0 && !empty($config)) : ?>
	<?php $this->partial("elements/admin/pagination", ["page" => $page, "plural" => $plural]); ?>
		
	<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
		<thead>
            <tr>
            	<th><input type="checkbox" /></th>
            	<?php foreach($config->display->index as $cdi) : ?>
                <th><?= $config->cols->$cdi->label ?></th>
                <?php endforeach; ?>
                <th></th>
            </tr>
        </thead>
        <tbody>
        	<?php foreach ($page->items as $crud): ?>
        	<tr class="odd">
        		<td><input type="checkbox" /></td>
        		<?php foreach($config->display->index as $cdi) : ?>
                <td>
                	<?= strip_tags($crud->$cdi) ?>
                </td>
                <?php endforeach; ?>

                <td class="center">
                    
                	<?php echo $this->tag->linkTo(["admin{$plural}/edit/" . $crud->id, '<i class="fa fa-edit"></i> Edit', "class" => "btn btn-default btn-xs"]); ?>  
                	<?php echo $this->tag->linkTo(["admin{$plural}/delete/" . $crud->id, '<i class="fa fa-trash"></i> Delete', "class" => "btn btn-default btn-xs"]); ?>

                </td>
        	</tr>	
        	<?php endforeach; ?>
        </tbody>
	</table>

	<?php $this->partial("elements/admin/pagination", ["page" => $page, "plural" => $plural]); ?>
<?php else: ?>
	<center>
		<font color="red">
			No <?= $plural ?> existed or config file not found!
		</font>
	</center>
<?php endif; ?>

