<p>
	<?php echo $this->tag->linkTo(["admin{$plural}/new", "ADD NEW", "class" => "btn btn-primary"]); ?>  
</p>

<?php if(count($page->items) > 0 && !empty($config)) : ?>
	<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
		<thead>
            <tr>
            	<th><input type="checkbox" /></th>
            	<?php foreach($config->display->index as $cdi) : ?>
                <th><?= $config->cols->$cdi->label ?></th>
                <?php endforeach; ?>
                <th></th>
            </tr>
        </thead>
        <tbody>
        	<?php foreach ($page->items as $crud): ?>
        	<tr class="odd">
        		<td><input type="checkbox" /></td>
        		<?php foreach($config->display->index as $cdi) : ?>
                <td>
                	<?= strip_tags($crud->$cdi) ?>
                </td>
                <?php endforeach; ?>

                <td class="center">
                	<?php echo $this->tag->linkTo(["admin{$plural}/edit/" . $crud->id, "Edit", "class" => "btn btn-primary btn-xs"]); ?>  
                	<?php echo $this->tag->linkTo(["admin{$plural}/delete/" . $crud->id, "Delete", "class" => "btn btn-danger btn-xs"]); ?>

                </td>
        	</tr>	
        	<?php endforeach; ?>
        </tbody>
	</table>

	<?php if(isset($page->total_pages) && $page->total_pages > 1) : ?>
		<div class="row">
		    <div class="col-sm-2">
		        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
		            Page <?= $page->current, "/", $page->total_pages ?>
		        </p>
		    </div>
		    <div class="col-sm-10">
		        <nav>
		            <ul class="pagination">
		                <li>
		                	<?= $this->tag->linkTo("admin{$plural}/index", "First") ?>
		                </li>
		                <li>
		                	<?= $this->tag->linkTo("admin{$plural}/index?page=" . $page->before, "Previous") ?>
		                </li>
		                <?php for($i = 1; $i <= $page->total_pages; $i++) : ?>
		                <li>
		                	<?= $this->tag->linkTo("admin{$plural}/index?page=".$i, $i) ?>
		                </li>	
		                <?php endfor; ?>
		                <li>
		                	<?= $this->tag->linkTo("admin{$plural}/index?page=" . $page->next, "Next") ?>
		                </li>
		                <li>
		                	<?= $this->tag->linkTo("admin{$plural}/index?page=" . $page->last, "Last") ?>
		                </li>
		            </ul>
		        </nav>
		    </div>
		</div>
	<?php endif; ?>
<?php else: ?>
	<center>
		<font color="red">
			No <?= $plural ?> existed or config file not found!
		</font>
	</center>
<?php endif; ?>

