<?php $this->partial("elements/admin/header"); ?>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $mt ?></h3>
                    </div>
                    <div class="panel-body">
                        <?= $this->getContent() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php $this->partial("elements/admin/footer"); ?>